name: Python CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install uv and sync dependencies
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Sync project dependencies
        run: uv sync --group dev

      - name: Lint with Ruff
        run: make lint

      - name: Check license headers
        run: |
          make add-license-headers
          if ! git diff --quiet; then
            echo "License headers are missing or incorrect. Please run 'make add-license-headers' to fix.";
            git diff --name-only
            exit 1;
          fi

      - name: Check translations
        run: make babel-check

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.14"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install uv and sync dependencies
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78

      - name: Sync project dependencies
        run: uv sync --group dev
        working-directory: horus-runtime

      - name: Run tests with coverage
        run: make test

      - name: Upload coverage report
        uses: actions/upload-artifact@v6
        if: matrix.python-version == '3.13'
        with:
          name: coverage-html-report
          path: htmlcov/
          retention-days: 5
